---
---

<h1> Past Meetings </h1>

```{r, echo = FALSE, message = FALSE, warning = FALSE }
library(knitr)
library(tidyverse)
library(kableExtra)
```

## Fall 2023 Schedule 
```{r, echo = FALSE, message = FALSE, warning = FALSE }
tib = tibble(
  `Topics` = c(
    "How to set up your computer as a Statistician",
    "Intro to Python",
    "Intro to Latex"),
  `Date` = c(
    "September 19, 2023; 11:45 AM - 12:45 PM", 
     "October 11, 2023; 11:45 AM - 12:45 PM",
     "November 15, 2023; 11:45 AM - 12:45 PM")
  ,
  `Location` = c(
    "ARB 532A",
    "Hammer LL103",
    "Hammer LL103")
)
kable(tib, row.names = FALSE) %>%
  kable_styling(bootstrap_options = "striped") %>%
  column_spec(1, width = "8em") %>%
  column_spec(2, width = "20em") %>%
  column_spec(3, width = "15em")
```

## Spring 2023 Schedule 
```{r, echo = FALSE, message = FALSE, warning = FALSE }
tib = tibble(
  `Topics` = c(
    "Drawing DAGs in R, Colab with CILG",
    "Making Presentations with Beamer"),
  `Date` = c(
    "Feburary 14, 2023; 11:45 AM - 12:45 PM", 
     "April 11, 2023; 11:45 AM - 12:45 PM")
  ,
  `Location` = c(
    "ARB 532A",
    "Hammer 312")
)
kable(tib, row.names = FALSE) %>%
  kable_styling(bootstrap_options = "striped") %>%
  column_spec(1, width = "8em") %>%
  column_spec(2, width = "20em") %>%
  column_spec(3, width = "15em")
```


## Fall 2022 Schedule
```{r, echo = FALSE, message = FALSE, warning = FALSE }
tib = tibble(
  `Topics` = c(
    "How to Set Up Your Computer as a Statistician ",
    "Latex + Beamer",
    "Python",
    #"TBD",
   # "Beamer Presentations with Career China",
    "RShiny"),
  `Date` = c(
    "September 20, 2022; 11:45 AM - 12:45 PM", 
    "October 18, 2022; 11:45 AM - 12:45 PM", 
     "November 1, 2022; 11:45 AM - 12:45 PM", 
   # "Mar. 30, 2022; 11:30 - 1:00pm",
  #  "April 13, 2022; 11:30 - 12:30pm",
     "November 29, 2022; 11:45 AM - 12:45 PM")
  ,
  `Location` = c(
    "Hammer LL203",
    "Hammer 312",
    "Hammer 312",
    #"TBD",
    #"Zoom",
    "Hammer LL210")
)
kable(tib, row.names = FALSE) %>%
  kable_styling(bootstrap_options = "striped") %>%
  column_spec(1, width = "8em") %>%
  column_spec(2, width = "20em") %>%
  column_spec(3, width = "15em")
```

## Spring 2022 Schedule
```{r, echo = FALSE, message = FALSE, warning = FALSE }
tib = tibble(
  `Topics` = c(
    "SQL ",
    "R-Shiny",
    "Cluster Computing",
    #"TBD",
    "Beamer Presentations with Career China",
    "gtsummary with Daniel Sjoberg"),
  `Date` = c(
    "Feb. 8, 2022; 12:00 - 1:00pm", 
    "Feb. 23, 2022; 12:00 - 1:00pm", 
    "Mar. 16, 2022; 11:30 - 1:00pm", 
   # "Mar. 30, 2022; 11:30 - 1:00pm",
    "April 13, 2022; 11:30 - 12:30pm",
    "April 27, 2022; 11:30 - 1:00pm")
  ,
  `Location` = c(
    "Zoom",
    "Zoom",
    "Zoom",
    #"TBD",
    "Zoom",
    "Zoom")
)
kable(tib, row.names = FALSE) %>%
  kable_styling(bootstrap_options = "striped") %>%
  column_spec(1, width = "8em") %>%
  column_spec(2, width = "20em") %>%
  column_spec(3, width = "15em")

```


## Spring 2021 Schedule

```{r, echo = FALSE, message = FALSE, warning = FALSE }
tib = tibble(
  `Topics` = c(
    "Website Design: How to market yourself with Christian Pascual", 
    "Intro to Cluster computing",
    "gtsummary R package"),
  `Date` = c(
    "January 20, 2021; 12:00 - 1:00pm", 
    "March 31, 2021; 12:00 - 1:00pm", 
    "April 27, 2021; 12:00 - 1:00pm")
  ,
  `Location` = c(
    "Zoom",
    "Zoom",
    "Zoom")
)

kable(tib, row.names = FALSE) %>%
  kable_styling(bootstrap_options = "striped") %>%
  column_spec(1, width = "8em") %>%
  column_spec(2, width = "20em") %>%
  column_spec(3, width = "15em")
```

## Fall 2020 Schedule

```{r, echo = FALSE, message = FALSE, warning = FALSE }
tib = tibble(
  `Topics` = c(
    "Panel: Best practices as a graduate student", 
    "Introduction To LaTeX", 
    "SQL with Career China Club", 
    "GGplot packages",
    "Python Tutorial"),
  `Date` = c(
    "September 16, 2020; 11:30 - 12:30pm", 
    "September 30, 2020; 11:30 - 12:30pm", 
    "October 14, 2020; 11:30 - 12:30pm", 
    "November 13, 2020; 11:30 - 12:30pm", 
    "December 9, 2020; 11:30 - 12:30pm")
  ,
  `Location` = c(
    "Zoom",
    "Zoom",
    "Zoom",
    "Zoom",
    "Zoom")
)

kable(tib, row.names = FALSE) %>%
  kable_styling(bootstrap_options = "striped") %>%
  column_spec(1, width = "8em") %>%
  column_spec(2, width = "20em") %>%
  column_spec(3, width = "15em")
```


## Spring 2020 Schedule

```{r, echo = FALSE, message = FALSE, warning = FALSE }
tib = tibble(
  `Topic` = c("Introduction to Python", 
              "Introduction to SQL"),
  `Date` = c("February 10, 2020; 4 - 4:50pm", 
             "March 2, 2020; 4 - 4:50pm"),
  `Location` = c(
    "Hammer LL103", 
    "Hammer LL103")
)

kable(tib, row.names = FALSE) %>%
  kable_styling(bootstrap_options = "striped") %>%
  column_spec(1, width = "8em") %>%
  column_spec(2, width = "20em") %>%
  column_spec(3, width = "15em")
```

## Fall 2019 Schedule

```{r, echo = FALSE, message = FALSE, warning = FALSE }
tib = tibble(
  `Topic` = c("Speaker Panel", 
              "Using LaTeX in Overleaf & RMarkdown", 
              "A Biostatistician's Website", 
              "caret: Streamlining Model Tuning"),
  `Date` = c("September 9, 2019; 4 - 4:50pm", 
             "October 14, 2019; 4 - 4:50pm", 
             "November 11, 2019; 4 - 4:50pm", 
             "December 2, 2019; 4 - 4:50pm"),
  `Location` = c(
    "Hammer LL203", 
    "Hammer LL107", 
    "Hammer LL107", 
    "Hammer LL107")
)

kable(tib, row.names = FALSE) %>%
  kable_styling(bootstrap_options = "striped") %>%
  column_spec(1, width = "8em") %>%
  column_spec(2, width = "20em") %>%
  column_spec(3, width = "15em")
```


## Spring 2019 Schedule

```{r, echo=FALSE, comment=FALSE, message=FALSE}
event1 <- c("January 28, 2019", "Intermediate Python", "Christian Pascual")
event2 <- c("March 5, 2019", "Interactive visualization using RStudio’s Shiny", "Julia Wrobel")
event3 <- c("March 19, 2019", "", "Angel Garcia de la Garza")
event4 <- c("April 29, 2019", "Making an R Package", "Nick Williams")

schedule <- rbind(event1, event2, event3, event4)
colnames(schedule) <- c("Date","Title", "Presenters")

kable(schedule, row.names = FALSE) %>%
  kable_styling(bootstrap_options = "striped") %>%
  column_spec(1, width = "8em") %>%
  column_spec(2, width = "20em") %>%
  column_spec(3, width = "15em")
```

## Fall 2018 Schedule

```{r, echo=FALSE, comment=FALSE, message=FALSE}
event1 <- c("", "Panel of Speakers", "")
event2 <- c("September 24, 2018", "Using LaTeX", "Yutao Liu")
event3 <- c("October 30, 2018", "Python for Beginners", "Christian Pascual")
event3 <- c("November 19, 2018", "Working with maps in R", "Angel Garcia de la Garza")
event4 <- c("December 3, 2018", "", "")

schedule <- rbind(event1,event2,event3,event4)
colnames(schedule) <- c("Date","Title", "Presenters")

kable(schedule, row.names = FALSE) %>%
  kable_styling(bootstrap_options = "striped") %>%
  column_spec(1, width = "8em") %>%
  column_spec(2, width = "20em") %>%
  column_spec(3, width = "15em")
```

## Spring 2018 Schedule

```{r, echo=FALSE, comment=FALSE, message=FALSE}
event1 <- c("February 5, 2018", "General Meeting", "Hartaig Singh and Margie Hannum")
event2 <- c("March 5, 2018", " Data Science with Python", "Michael Figueroa (from Columbia Data Science Institute)")
event3 <- c("March 19, 2018", "Introduction to Illustrator for Scientists \n \n
 [Link to download materials and resources](http://tinyurl.com/k8ya4gk)", "Anjile An")
event4 <- c("April 2, 2018", "Stan for Bayesian Network Analysis", "Yutao Liu")

schedule <- rbind(event1,event2,event3,event4)
colnames(schedule) <- c("Date","Title", "Presenters")

kable(schedule, row.names = FALSE) %>%
  kable_styling(bootstrap_options = "striped") %>%
  column_spec(1, width = "8em") %>%
  column_spec(2, width = "20em") %>%
  column_spec(3, width = "15em")
```

## Fall 2017 Schedule

```{r, echo=FALSE, comment=FALSE, message=FALSE}
event1 <- c("September 11, 2017", 
            "How to Set Up Your Computer as a Statistician \n \n [Notes from presentation and panel discussion](resources_files/computer_091117.pdf)", 
            "Jeff Goldsmith \n \n Student Panel: Yutao Liu, Julia Wrobel, Karissa Whiting, and Brady Rippon")
event2 <- c("October 9, 2017", 
            "Split, Match, Replace and other ways to juggle multiple data types in R \n \n [Sample Genomic Data](resources_files/Manipulation_Data.zip) \n \n [Data Manipulation Tutorial Code](resources_files/cbcc_100917.R)", 
            "Margaret Hannum")
event3 <- c("October 16, 2017", 
            "LaTeX Workshop \n \n [LaTeX with Overleaf Slides](resources_files/latex_101617.pdf)", 
            "Brady Rippon")
event4 <- c("November 13, 2017", 
            "Using the OSX Terminal \n \n [Link to Julia's Tutorial](http://juliawrobel.com/tutorials/osx_terminal.html)", 
            "Julia Wrobel")
event5 <- c("December 4, 2017", 
            "Data Collection with SQL", 
            "Hartaig Singh")


schedule <- rbind(event1,event2,event3,event4,event5)
colnames(schedule) <- c("Date","Title", "Presenters")

kable(schedule, row.names = FALSE) %>%
  kable_styling(bootstrap_options = "striped") %>%
  column_spec(1, width = "8em") %>%
  column_spec(2, width = "20em") %>%
  column_spec(3, width = "15em")
```

## Spring 2017

```{r, echo=FALSE, comment=FALSE, message=FALSE}
event1 <- c("January 19, 2017", 
            "Introduction to R and R Markdown \n \n [rMarkdown Exercise](resources_files/RMD_Exercise.pdf) \n \n [Ariel's rMarkdown Slides](resources_files/RMD_slides.pdf) [Ariel's sample rMarkdown file](resources_files/SampleRMD.rmd)", 
            "Ariel Chernofsky")
event2 <- c("February 23, 2017", 
            "The beauty of ggplot2 \n \n [ggplot2 pdf](resources_files/ggplot2.pdf) \n \n [Jihui's rMarkdown file on ggplot2](resources_files/ggplot2.rmd)", 
            "Jihui Lee")
event3 <- c("March 23, 2017", 
            "Interactive visualization using RStudio’s Shiny \n \n [shiny slides](resources_files/shinySlides.html) \n \n
[hospitals dataset](resources_files/Hospital.csv) \n \n
[hospitals app](resources_files/hospitalApp.zip)", 
            "Julia Wrobel")
event4 <- c("April 20, 2017", 
            "Using GitHub for collaboration and version control \n \n [Jeff's slides](http://p8105.com/git.html)", 
            "Jeff Goldsmith")

schedule <- rbind(event1,event2,event3,event4)
colnames(schedule) <- c("Date","Title", "Presenters")

kable(schedule, row.names = FALSE) %>%
  kable_styling(bootstrap_options = "striped") %>%
  column_spec(1, width = "8em") %>%
  column_spec(2, width = "20em") %>%
  column_spec(3, width = "15em")



```


<p>&nbsp;</p>
