---
title: Resources
output:
  html_document:
    toc: true
    toc_float: true
---

This is a list of all the resources students have created for the Computing Club:


## General Advice

How to Set Up Your Computer as a Statistician

* [2024 Notes from presentation and panel discussion](resources_files/20240916_cc_computer_setup_notes.docx)
* [2023 Notes from presentation and panel discussion](resources_files/meeting_sept23.docx)
* [2022 Notes from presentation and panel discussion](resources_files/meeting_sept20.docx)
* [2021 Notes from presentation and panel discussion](resources_files/computing_club_minutes_20212109.pdf)
* [2018 Notes from presentation and panel discussion](resources_files/Computing_Club Minutes_September_2018.pdf)
* [2017 Notes from presentation and panel discussion](resources_files/computer_091117.pdf)

## R Resources

Introduction to R and R Markdown with Ariel Chernofsky.

* [RMarkdown Exercise](resources_files/RMD_Exercise.pdf)
* [Ariel's rMarkdown Slides](resources_files/RMD_slides.pdf)
* [Ariel's sample rMarkdown file](resources_files/SampleRMD.rmd)

## Data manipulation

Margaret Hannum's presentation with genomic data.

* [Sample Genomic Data](resources_files/Manipulation_Data.zip)
* [Data Manipulation Tutorial Code](resources_files/cbcc_100917.R)

## RStudio

Dr. Julia Wrobel's presentation

* [Shiny slides](resources_files/shinySlides.html)
* [Hospitals .csv](resources_files/Hospital.csv)
* [Hospitals app](resources_files/hospitalApp.zip)

## R Shiny 

Amy's Fall 2022 Presentation and Demo Files:

* [Slides](resources_files/shiny_pres/cc_pres_nov_2022.pdf)
* [base file](resources_files/shiny_pres/shiny_base_nov2022.R)
* [Shiny R Script Example](resources_files/shiny_pres/shiny_example.R)

Fiona and Amy's Spring 2022 Presentation and Demo Resources 

* [Slide from 2022 Presentation](resources_files/shiny_pres/cc_shiny_pres.pdf)
* [Shiny R Script Example](resources_files/shiny_pres/shiny_example.R)

## Software for DAGs

Amy & Charly 2023

* [Slide from 2023 Presentation](resources_files/DAG_pres.html)
* [TikZ Tex file](resources_files/dag_tex.tex)
* [arxiv paper](https://arxiv.org/pdf/2305.12006.pdf)


## Illustrator

Introduction to Illustrator with Anjile An. 

* [Link to download materials and resources](http://tinyurl.com/k8ya4gk)


## HTML and CSS

Introduction to HTML and CSS with Derek Lamb

* [Presentation File](resources_files/html_and_css_for_data_science.pptx)

## OSX Terminal

Using the OSX Terminal with Julia Wrobel. 

* [Link to Julia's tutorial](http://juliawrobel.com/tutorials/osx_terminal.html)

## LaTeX

Lupe + Safiya's Fall 2024 Tutorial

* [LaTeX output](resources_files/lupe_intro_to_latex_2025.pdf)
* [LaTeX in R code](resources_files/safiya_latex_pres_2025.pdf)
* [LaTeX in R output](resources_files/safiya_latex_pres_2025.Rmd)


Lupe + Ziyi's Fall 2023 Tutorial

* [.pdf output file](resources_files/latex/intro_to_latex.pdf)
* [.tex file](resources_files/latex/intro_to_latex_lupe.tex)
* [.pdf tutorial](resources_files/latex/latex_cheat_sheet.pdf)
* [.zip tutorial](resources_files/latex/latex_cheat_sheet.zip)


Jimmy + Ziyi's Fall 2022 Tutorial

* [.pdf output file](resources_files/jimmy_pres/intro2latex.pdf)
* [.tex file](resources_files/jimmy_pres/intro2latex.tex)

Zilan + Charly's Fall 2021 Tutorial

* [.pdf output file](resources_files/introduction_to_latex_2021_zilan/Introduction_to_LaTex.pdf)
* [.tex file](resources_files/introduction_to_latex_2021_zilan/main.tex)
* [photo needed for .tex file](resources_files/introduction_to_latex_2021_zilan/cu.jpg)

Christian's Fall 2019 Tutorial:

- [.Rmd version of tutorial](resources_files/latex-presentation.Rmd)
- [.html version of tutorial](resources_files/latex-presentation.html)

Yutao's Fall 2018 Tutorial

* [Overleaf Tutorial](https://v2.overleaf.com/read/fdxyszqvstzn)
* [.Rmd combining R Markdown and LaTeX equations](resources_files/computing-club-tutorial-latex.Rmd)
* [.html output](resources_files/computing-club-tutorial-latex.html)
* [.pdf output](resources_files/computing-club-tutorial-latex.pdf)

Brady Rippon's Fall 2017 Tutorial

* [LaTeX with Overleaf Slides](resources_files/latex_101617.pdf)

## Beamer 

Safiya Sirota Tutorial 2024:

* [.pdf](resources_files/beamer/beamer_presentation.pdf)
* [.tex](resources_files/beamer/beamer_presentation.tex)


Waveley Qiu Tutorial 2023:

* [Intro to Beamer in RMarkdown Pres](resources_files/intro_to_beamer.pdf)
* [Link to Github](https://github.com/waveley/intro_to_beamer)

Ruiyang + Jimmy's Spring 2022 Tutorial: 

* [basics in overleaf pdf](resources_files/beamer/beamer_basics_overleaf.pdf)
* [basics in overleaf tex](https://www.overleaf.com/read/dkbknhgfgfxy)
* [Special Topics pdf](resources_files/beamer/beamerSpecialTopics.pdf)
* [Special Topics Rmd](resources_files/beamer/beamerSpecialTopics.Rmd)

## Github

Using GitHub for collaboration and version control with Jeff Goldsmith

* [Jeff's slides](http://p8105.com/git.html)

## Python

Fall 2024 (Amy Pitts & Gustavo Garcia-Franceschini):

* [Slide  Show](resources_files/Python_tutorial_2020_amy.pdf)
* [Blank Google Colab](https://colab.research.google.com/drive/1g4343nOLPo1p9MpvOEAnPM426lXDblph#scrollTo=xiZIneWtEdYs)
* [Completed Google Colab](https://colab.research.google.com/drive/1tvqgGZG3k6I9R9THvQFl6R5JuYafWELX)

Fall 2023 (Safiya Sirota & Gustavo Garcia-Franceschini):

* [Slide  Show](resources_files/Python Presentation 2023.pdf)
* [Blank Google Colab](https://colab.research.google.com/drive/1g4343nOLPo1p9MpvOEAnPM426lXDblph#scrollTo=xiZIneWtEdYs)
* [Completed Google Colab](https://colab.research.google.com/drive/1tvqgGZG3k6I9R9THvQFl6R5JuYafWELX)

Fall 2022 (Safiya Sirota & Paula Wu):

* [Slides for 2022 Presentation](resources_files/Safiya_Python_Presentation_2022.pdf)
* [Google Colab for 2022 Presentatio](https://colab.research.google.com/drive/1II3LWtEW1wnlFFFYMCWq6gAHxY8ngMYS?usp=sharing)

Fall 2021 (Safiya Sirota & Paula Wu):

* [Slides for 2021 Presentation](resources_files/Python_Pres_fall_2021.pdf)
* [Google Colab for 2021 Presentation](https://colab.research.google.com/drive/1aZnKgFJRLZtT37AS8fM4yeOd_YbH9TuI?usp=sharing)

Fall 2020 (Amy Pitts & Muhire Honorine Kwizera):

* [Slide Show 2020 Workshop](resources_files/Python_tutorial_2020_amy.pdf)


## Portfolio Work

* [Angel's .Rmd version of tutorial](resources_files/_site.yml)
* [Christian's Notes on pages and CSS](resources_files/website-presentation.html)

## SQL

Olivia's SQL 2024 Presentation

*[powerpoint slideshow](resources_files/SQL_Presentation.pdf)


Colby Lewis 2022 Presentation 

* [ powerpoint slideshow](resources_files/SQL_for_Tidyverse_Pros.pptx)

Christian's 2020 Workshop

* [.db file for workshop](resources_files/sql-workshop.db)
* [.html file of workshop](resources_files/sql-workshop.html)
* [.Rmd file of workshop](resources_files/sql-workshop.Rmd)


## Cluster 

Zilan's 2022 Workshop 

* [Slide Show](resources_files/Intro_to_cluster.pdf)

## GIS

Jake's Presentation Spring 2024

* [Powerpoint](resources_files/cc_gis_jake.pptx)

## Libraries

### `gtsummary`

Lupe's Presentation Spring 2024

* [gtsummary tutorial pdf](resources_files/gtsummary_cc.pdf)
* [gtsummary tutorial Rmd](resources_files/gtsummary_cc.Rmd)

Daniels Sjoberg: 

* [Slide Show](http://www.danieldsjoberg.com/gtsummary-Columbia-Computing-Club/#1)

### `sf`

Gustavo' Presentation Spring 2024

* [.html file](resources_files/sf_tutorial.html)
* [.Rmd file](resources_files/sf_tutorial.Rmd)


### `maps`

* [.html file](resources_files/maps_tutorial.html)
* [.csv file](resources_files/provinces_italy.csv)

### `caret`

* [Angel's .Rmd version of tutorial](resources_files/caret_tutorial_computingclub.Rmd)

### `ggplot2`

Jihui Lee's presentation

* [.pdf file](resources_files/ggplot2.pdf)
* [Jihui's rMarkdown file on ggplot2](resources_files/ggplot2.rmd)


