---
title: "Schedule"
---

The club meets monthly on Tuesday from 4:00-5:00pm in Hammer LL205 unless otherwise noted.

### Fall 2018 Schedule

* _September 11, 2018:_ How to Set Up Your Computer as a Statistician with TBA
* _September 25, 2018:_ TBA
* _October 30, 2018:_ TBA
* _November 27, 2018:_ TBA

### Spring 2018 Schedule

* _February 5, 2018:_ General Meeting hosted by Hartaig Singh and Margie Hannum. Hammer LL205.
* _March 5, 2018:_ Data Science with Python with Michael Figueroa (from Columbia Data Science Institute). Hammer LL205.
* _March 19, 2018:_ Introduction to Illustrator for Scientists with Anjile An. Hammer LL103.
* _April 2, 2018:_ Stan for Bayesian Network Analysis with Yutao Liu. Hammer LL205.
* _May 7, 2018:_ TBA with TBA. Hammer LL205.

### Fall 2017 Schedule

* _September 11, 2017:_ How to Set Up Your Computer as a Statistician with Jeff Goldsmith. Student Panel: Yutao Liu, Julia Wrobel, Karissa Whiting, and Brady Rippon.
* _October 9, 2017:_ Split, Match, Replace and other ways to juggle multiple data types in R with Margaret Hannum.
* _October 16, 2017:_ LaTeX Workshop with Brady Rippon. In Biostats Computer Lab
* _November 13, 2017:_ Using the OSX Terminal with Julia Wrobel. Hammer LL204
* _December 4, 2017:_ Data Collection with SQL with Hartaig Singh. Hammer LL103

### Spring 2017

* _January 19:_ Introduction to R and R Markdown with Ariel Chernofsky
* _February 23:_ The beauty of ggplot2 with Jihui Lee
* _March 23:_ Interactive visualization using RStudio's Shiny with Julia Wrobel
* _April 20:_ Using GitHub for collaboration and version control with Jeff Goldsmith